// <auto-generated/>

// Field is never assigned to, it is initialized from the C API.
#pragma warning disable CS0649

namespace RawPowerLabs.DynamicAI.Native
{
    /// <summary>Create text modules backed by cloud LLM inference via the AIFactory backend.</summary>
    internal unsafe struct CloudTextModuleApi
    {
        /// <summary>Fill a cloud_text_module_params struct with default values.</summary>
        public delegate* unmanaged[Cdecl]<ref CloudTextModuleParameters, void> GetDefaultParams;

        /// <summary>Create a cloud text module. Fetches the project template on creation.</summary>
        public delegate* unmanaged[Cdecl]<int, ref CloudTextModuleParameters, int> Create;
    }
}
