// <auto-generated/>

// Field is never assigned to, it is initialized from the C API.
#pragma warning disable CS0649

namespace RawPowerLabs.DynamicAI.Native
{
    /// <summary>Manages context lifetime. A context owns all resources created within it.</summary>
    internal unsafe struct ContextApi
    {
        /// <summary>Create a new context.</summary>
        public delegate* unmanaged[Cdecl]<int> CreateContext;

        /// <summary>Destroy a context and free all resources owned by it.</summary>
        public delegate* unmanaged[Cdecl]<int, void> DestroyContext;
    }
}
