// <auto-generated/>
using System;
using System.IO;
using System.Runtime.InteropServices;
using static RawPowerLabs.DynamicAI.Native.CoreModule;

// Field is never assigned to, it is initialized from the C API.
#pragma warning disable CS0649

namespace RawPowerLabs.DynamicAI.Native
{
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct CoreInterface
    {
        private const uint Version = 0xDA100000;

        private static CoreInterface _instance;
        private static bool _initialized;

        public static CoreInterface* Instance
        {
            get
            {
                if (!_initialized) Initialize();
                fixed (CoreInterface* p = &_instance) return p;
            }
        }

        private static void Initialize()
        {
            var root = Path.GetDirectoryName(typeof(CoreInterface).Assembly.Location) ?? string.Empty;
            var logCb = new LogCallback(CoreDiagnostics.OnLog);
            dai_initialize(root, Marshal.GetFunctionPointerForDelegate(logCb));
            _instance = *(CoreInterface*)dai_get_api(Version);
            _initialized = true;
            AppDomain.CurrentDomain.ProcessExit += (_, _) => { dai_shutdown(); _initialized = false; };
        }

        /// <summary>Manages context lifetime. A context owns all resources created within it.</summary>
        public ContextApi Context;

        /// <summary>Shared invoke and destroy operations for both local and cloud text modules.</summary>
        public TextModuleApi TextModule;

        /// <summary>Create text modules backed by local llama.cpp inference.</summary>
        public LocalTextModuleApi LocalTextModule;

        /// <summary>Create text modules backed by cloud LLM inference via the AIFactory backend.</summary>
        public CloudTextModuleApi CloudTextModule;

        /// <summary>A key-value bag of input parameters for a text module invocation.</summary>
        public TextModuleInputApi TextModuleInput;

        /// <summary>A key-value bag of output values from a text module invocation.</summary>
        public TextModuleResultApi TextModuleResult;
    }
}
