// <auto-generated/>
using System;
using System.Runtime.InteropServices;

namespace RawPowerLabs.DynamicAI.Native
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void LogCallback(LogLevel level, IntPtr text, IntPtr size);

    internal static class CoreModule
    {
        [DllImport("dai", CharSet = CharSet.Ansi)]
        public static extern void dai_initialize(string root, IntPtr logCallback);

        [DllImport("dai")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool dai_check_api(uint version);

        [DllImport("dai")]
        public static unsafe extern void* dai_get_api(uint version);

        [DllImport("dai")]
        public static extern void dai_shutdown();
    }
}
