// <auto-generated/>

// Field is never assigned to, it is initialized from the C API.
#pragma warning disable CS0649

namespace RawPowerLabs.DynamicAI.Native
{
    /// <summary>Create text modules backed by local llama.cpp inference.</summary>
    internal unsafe struct LocalTextModuleApi
    {
        /// <summary>Fill a text_module_params struct with default values.</summary>
        public delegate* unmanaged[Cdecl]<ref TextModuleParameters, void> GetDefaultParams;

        /// <summary>Fill a text_module_invoke_params struct with default values.</summary>
        public delegate* unmanaged[Cdecl]<ref TextModuleInvokeParameters, void> GetDefaultInvokeParams;

        /// <summary>Create a local text module from a GGUF model file.</summary>
        public delegate* unmanaged[Cdecl]<int, ref TextModuleParameters, byte*, byte*, int> Create;
    }
}
