// <auto-generated/>

// Field is never assigned to, it is initialized from the C API.
#pragma warning disable CS0649

namespace RawPowerLabs.DynamicAI.Native
{
    /// <summary>A key-value bag of input parameters for a text module invocation.</summary>
    internal unsafe struct TextModuleInputApi
    {
        /// <summary>Create an input bag associated with a text module.</summary>
        public delegate* unmanaged[Cdecl]<int, int, int> Create;

        /// <summary>Destroy an input bag.</summary>
        public delegate* unmanaged[Cdecl]<int, int, void> Destroy;

        /// <summary>Set an integer value by key.</summary>
        public delegate* unmanaged[Cdecl]<int, int, byte*, int, bool> SetInt;

        /// <summary>Get an integer value by key.</summary>
        public delegate* unmanaged[Cdecl]<int, int, byte*, ref int, bool> GetInt;

        /// <summary>Set a string value by key.</summary>
        public delegate* unmanaged[Cdecl]<int, int, byte*, byte*, nint, bool> SetString;

        /// <summary>Get a string value by key. Call with buffer=null to query the required size, then again with an allocated buffer.</summary>
        public delegate* unmanaged[Cdecl]<int, int, byte*, byte*, ref nint, bool> GetString;
    }
}
