// <auto-generated/>

// Field is never assigned to, it is initialized from the C API.
#pragma warning disable CS0649

namespace RawPowerLabs.DynamicAI.Native
{
    /// <summary>Shared invoke and destroy operations for both local and cloud text modules.</summary>
    internal unsafe struct TextModuleApi
    {
        /// <summary>Fill a text_module_invoke_params struct with default values.</summary>
        public delegate* unmanaged[Cdecl]<ref TextModuleInvokeParameters, void> GetDefaultInvokeParams;

        /// <summary>Invoke a text module and return a handle to the result.</summary>
        public delegate* unmanaged[Cdecl]<int, int, ref TextModuleInvokeParameters, int, int> Invoke;

        /// <summary>Destroy a text module and free its resources.</summary>
        public delegate* unmanaged[Cdecl]<int, int, void> Destroy;
    }
}
