// <auto-generated/>

// Field is never assigned to, it is initialized from the C API.
#pragma warning disable CS0649

namespace RawPowerLabs.DynamicAI.Native
{
    /// <summary>A key-value bag of output values from a text module invocation.</summary>
    internal unsafe struct TextModuleResultApi
    {
        /// <summary>Destroy a result and free its resources.</summary>
        public delegate* unmanaged[Cdecl]<int, int, void> Destroy;

        /// <summary>Get an integer value by key.</summary>
        public delegate* unmanaged[Cdecl]<int, int, byte*, ref int, bool> GetInt;

        /// <summary>Get a string value by key. Call with buffer=null to query the required size, then again with an allocated buffer.</summary>
        public delegate* unmanaged[Cdecl]<int, int, byte*, byte*, ref nint, bool> GetString;
    }
}
