// <auto-generated/>
using System.Runtime.InteropServices;

namespace RawPowerLabs.DynamicAI
{
    /// <summary>Construction parameters for a cloud text module.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CloudTextModuleParameters
    {
        /// <summary>AIFactory backend base URL.</summary>
        public byte* AifactoryUrl;

        /// <summary>Design module backend base URL.</summary>
        public byte* DesignmoduleUrl;

        /// <summary>Zitadel auth server base URL.</summary>
        public byte* ZitadelUrl;

        /// <summary>Zitadel project ID for audience scope.</summary>
        public byte* ZitadelProjectId;

        /// <summary>Application project UUID.</summary>
        public byte* ProjectId;

        /// <summary>OAuth2 client ID.</summary>
        public byte* ClientId;

        /// <summary>OAuth2 client secret.</summary>
        public byte* ClientSecret;

        /// <summary>Model name, e.g. 'gpt-4o'.</summary>
        public byte* Model;
    }
}
