// <auto-generated/>
using System.Runtime.InteropServices;
using RawPowerLabs.DynamicAI.Native;

namespace RawPowerLabs.DynamicAI
{
    /// <summary>Construction parameters for a local text module.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct TextModuleParameters
    {
        /// <summary>Number of model layers to offload to GPU. int32_max means all layers.</summary>
        public int GpuLayers;

        public static unsafe TextModuleParameters GetDefault()
        {
            TextModuleParameters parameters = new TextModuleParameters();
            CoreInterface.Instance->LocalTextModule.GetDefaultParams(ref parameters);
            return parameters;
        }
    }
}
