// <auto-generated/>
using System.Runtime.InteropServices;
using RawPowerLabs.DynamicAI.Native;

namespace RawPowerLabs.DynamicAI
{
    /// <summary>Invocation parameters shared by local and cloud text modules.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public partial struct TextModuleInvokeParameters
    {
        /// <summary>RNG seed. uint32_max selects a random seed.</summary>
        public uint Seed;

        /// <summary>Sampling temperature.</summary>
        public float Temperature;

        /// <summary>Maximum tokens to generate. 0 uses the model default.</summary>
        public int PredictCount;

        /// <summary>Context window size in tokens. 0 uses the value from the model file.</summary>
        public uint ContextSize;

        /// <summary>Maximum logical batch size passed to llama_decode.</summary>
        public uint BatchSize;

        public static unsafe TextModuleInvokeParameters GetDefault()
        {
            TextModuleInvokeParameters parameters = new TextModuleInvokeParameters();
            CoreInterface.Instance->TextModule.GetDefaultInvokeParams(ref parameters);
            return parameters;
        }
    }
}
